### PR TITLE
Firebase signup/login

### PR DESCRIPTION
**Pull request by ahegazy**

### CODE REVIEW

**Review by adeen-s — COMMENTED** [review]
@ahegazy this PR overwrites the similar books feature. Apart from this, the code looks fine to me.

**Review by danivijay — COMMENTED** [review]
Merging latest project will do the trick, I guess.

**Comment by ahegazy** [comment]
@danivijay  i don't understand .. can you do it?

**Comment by adeen-s** [comment]
@ahegazy I would suggest looking into `git rebase` command. It would likely fix it for you.

**Comment by adeen-s** [comment]
Closing this in favour of #19

**Pull request closed without merging**
